### PR TITLE
Add files to deploy on dds

### PR DESCRIPTION
**Pull request by amadoukane96**
this PR also modify app to correct the local " cannot import name 'is_list_like" error

### CODE REVIEW

**Comment by amadoukane96** [comment]
please if ready to merge change the link to https://dash-gallery.plotly.host/dash-stock-tickers-demo-app in github

**Comment by xhluca** [comment]
@bcdunbar we should maybe merge this pr...

**Comment by bcdunbar** [comment]
@xhlulu I think this can be closed as I made the relevant changes when adding https://github.com/plotly/dash-stock-tickers-demo-app/pull/31

**Comment by xhluca** [comment]
Makes sense. I think we should check the deployment though because it
doesn't seem to be working correctly on the dds.

Sincerely,
Xing Han Lu

**Comment by bcdunbar** [comment]
If you're referring to the one currently deployed on gallery DDS it is likely @amadoukane96 deployed the earlier version w/ broken pandas_datareader and to his own account.

master ought to be fine though 🤞

**Comment by xhluca** [comment]
Sounds good. We should have a fte have access to push access to the dds app
or set up autodeploy like heroku. Maybe Hamza or Jose can help?

Sincerely,
Xing Han Lu

**Pull request closed without merging**
