### PR TITLE
fix: add missing runtime.txt

### PR DESCRIPTION
**Pull request by josegonzalez**
This app runs on python 2.7.14. Heroku defaults newly created apps to the latest stable, which at this time is 3.6.4.

Pinning the runtime.txt solves this problem for any demo pushes.

### CODE REVIEW

**Comment by scjody** [comment]
@plotly/dash Can someone review this?

Also do any of our other demo Dash Apps have this issue?

**Comment by bcdunbar** [comment]
@josegonzalez 💃 If you are able to merge go for it - otherwise I'll merge.

@scjody it looks like some have a runtime file and some don't. I'll update those that don't.

**Comment by josegonzalez** [comment]
@bcdunbar do you know what the deploy process is for getting this change live?

**Comment by bcdunbar** [comment]
@josegonzalez it is setup with auto-deploy on heroku. Deploy looks good.

**Pull request merged**
